// Every localStorage key name as it was before refactor chunk 6B renamed them, mapped to the
// KEYS entry that holds its name now ('group.property' in js/shared/storage/keys.js). Generated
// from main's keys.js at 6B, so these strings are the old names exactly as users' browsers and
// old backup files hold them. Some didn't change (mds_show_headshots, every mls_* key,
// shared_sleeper_league_id, tscore_page_cache). Don't edit: it records the past.
export const PRE_6B_KEYS = {
    'ds_active_draft_id': 'mds.activeDraftId',
    'ds_adp_meta': 'mds.adpMeta',
    'ds_avoids': 'mds.avoids',
    'ds_bye_warnings': 'mds.byeWarnings',
    'ds_darts': 'mds.darts',
    'ds_draftId': 'mds.draftId',
    'ds_draft_settings': 'mds.draftSettings',
    'ds_drafted': 'mds.drafted',
    'ds_drafts': 'mds.drafts',
    'ds_drafts_premigration_backup': 'mds.draftsPremigrationBackup',
    'ds_hide_guide_banner': 'mds.hideGuideBanner',
    'ds_hide_install_banner': 'mds.hideInstallBanner',
    'ds_hide_mls_banner': 'mds.hideMlsBanner',
    'ds_limits': 'mds.limits',
    'ds_meta': 'mds.meta',
    'ds_mobile_collapse_pref': 'mds.mobileCollapsePref',
    'ds_myTeam': 'mds.myTeam',
    'ds_players': 'mds.players',
    'ds_raw_picks': 'mds.rawPicks',
    'ds_stacks': 'mds.stacks',
    'ds_storage_version': 'mds.storageVersion',
    'ds_targets': 'mds.targets',
    'ds_total_picks': 'mds.totalPicks',
    'ds_tscore': 'mds.tscore',
    'ds_username': 'mds.username',
    'mds_show_headshots': 'mds.showHeadshots',
    'mds_season_active_league': 'mls.activeLeague',
    'mds_season_early_teams': 'mls.earlyTeams',
    'mds_season_leagues': 'mls.leagues',
    'mds_season_locks_map': 'mls.locksMap',
    'mds_season_manual_bench': 'mls.manualBench',
    'mds_season_manual_starters': 'mls.manualStarters',
    'mds_season_market': 'mls.market',
    'mds_season_market_updated': 'mls.marketUpdated',
    'mds_season_ros': 'mls.ros',
    'mds_season_ros_updated': 'mls.rosUpdated',
    'mds_season_sos': 'mls.sos',
    'mds_season_weekly': 'mls.weekly',
    'mds_season_weekly_updated': 'mls.weeklyUpdated',
    'mls_autolock_overrides_map': 'mls.autolockOverridesMap',
    'mls_has_optimized': 'mls.hasOptimized',
    'mls_has_seen_rankings_toast': 'mls.hasSeenRankingsToast',
    'mls_hide_draft_banner': 'mls.hideDraftBanner',
    'mls_hide_guide_banner': 'mls.hideGuideBanner',
    'mls_hide_sleeper_sync_banner': 'mls.hideSleeperSyncBanner',
    'mls_lineup_rankings_stamps': 'mls.lineupRankingsStamps',
    'mls_lineup_settings': 'mls.lineupSettings',
    'mls_market_settings': 'mls.marketSettings',
    'mls_power_settings': 'mls.powerSettings',
    'mls_ranking_sets_ros': 'mls.rankingSetsRos',
    'mls_ranking_sets_weekly': 'mls.rankingSetsWeekly',
    'mls_show_headshots': 'mls.showHeadshots',
    'mls_sim_settings': 'mls.simSettings',
    'mls_sync_logs': 'mls.syncLogs',
    'mls_trade_settings': 'mls.tradeSettings',
    'mls_waiver_scan_settings': 'mls.waiverScanSettings',
    'mds_handoff_roster': 'shared.handoffRoster',
    'shared_sleeper_league_id': 'shared.sleeperLeagueId',
    'mds_tscore_cache': 'tscore.cache',
    'mds_tscore_cache_updated': 'tscore.cacheUpdated',
    'tscore_page_cache': 'tscore.pageCache',
};

// The one dynamic key: one player pool per MDS draft profile.
export const PRE_6B_DRAFT_POOL_PREFIX = 'ds_players_';
