// tscore_data.js
// 2026 Predictive T-Score Data for Skill Positions
const tScoreData = {
    // Wide Receivers
    "pukanacua": { s: 96.44, l: "Elite", c: "label-elite" },
    "jaxonsmithnjigba": { s: 94.51, l: "Elite", c: "label-elite" },
    "jamarrchase": { s: 87.21, l: "Elite", c: "label-elite" },
    "amonrastbrown": { s: 86.42, l: "Elite", c: "label-elite" },
    "georgepickens": { s: 84.14, l: "Elite", c: "label-elite" },
    "drakelondon": { s: 76.42, l: "Elite", c: "label-elite" },
    "ceedeelamb": { s: 74.66, l: "High-End Starter", c: "label-high" },
    "rasheerice": { s: 74.09, l: "High-End Starter", c: "label-high" },
    "nicocollins": { s: 73.76, l: "High-End Starter", c: "label-high" },
    "chrisolave": { s: 72.49, l: "High-End Starter", c: "label-high" },
    "davanteadams": { s: 71.36, l: "High-End Starter", c: "label-high" },
    "zayflowers": { s: 68.93, l: "High-End Starter", c: "label-high" },
    "ajbrown": { s: 68.49, l: "Strong Starter", c: "label-strong" },
    "tetairoamcmillan": { s: 66.61, l: "Strong Starter", c: "label-strong" },
    "courtlandsutton": { s: 66.56, l: "Strong Starter", c: "label-strong" },
    "justinjefferson": { s: 66.19, l: "Strong Starter", c: "label-strong" },
    "alecpierce": { s: 65.96, l: "Strong Starter", c: "label-strong" },
    "jamesonwilliams": { s: 65.52, l: "Strong Starter", c: "label-strong" },
    "michaelwilson": { s: 65.45, l: "Strong Starter", c: "label-strong" },
    "stefondiggs": { s: 64.77, l: "Strong Starter", c: "label-strong" },
    "wandalerobinson": { s: 64.01, l: "Strong Starter", c: "label-strong" },
    "terrymclaurin": { s: 63.87, l: "Strong Starter", c: "label-strong" },
    "jaylenwaddle": { s: 63.21, l: "Strong Starter", c: "label-strong" },
    "romeodunze": { s: 62.97, l: "Quality Contributor", c: "label-quality" },
    "christianwatson": { s: 62.93, l: "Quality Contributor", c: "label-quality" },
    "teehiggins": { s: 62.75, l: "Quality Contributor", c: "label-quality" },
    "rickypearsall": { s: 62.47, l: "Quality Contributor", c: "label-quality" },
    "devontasmith": { s: 62.39, l: "Quality Contributor", c: "label-quality" },
    "dkmetcalf": { s: 61.55, l: "Quality Contributor", c: "label-quality" },
    "jakobimeyers": { s: 60.32, l: "Quality Contributor", c: "label-quality" },
    "parkerwashington": { s: 58.83, l: "Quality Contributor", c: "label-quality" },
    "keenanallen": { s: 58.61, l: "Quality Contributor", c: "label-quality" },
    "emekaegbuka": { s: 58.37, l: "Quality Contributor", c: "label-quality" },
    "quentinjohnston": { s: 57.97, l: "Quality Contributor", c: "label-quality" },
    "romeodoubs": { s: 57.71, l: "Quality Contributor", c: "label-quality" },
    "laddmcconkey": { s: 57.23, l: "Quality Contributor", c: "label-quality" },
    "mikeevans": { s: 56.72, l: "Quality Contributor", c: "label-quality" },
    "jauanjennings": { s: 56.51, l: "Quality Contributor", c: "label-quality" },
    "brianthomas": { s: 56.16, l: "Quality Contributor", c: "label-quality" },
    "marvinharrison": { s: 55.08, l: "Boom/Bust", c: "label-boom" },
    "michaelpittman": { s: 53.96, l: "Boom/Bust", c: "label-boom" },
    "deebosamuel": { s: 53.75, l: "Boom/Bust", c: "label-boom" },
    "troyfranklin": { s: 53.55, l: "Boom/Bust", c: "label-boom" },
    "khalilshakir": { s: 53.09, l: "Boom/Bust", c: "label-boom" },
    "jordanaddison": { s: 52.92, l: "Boom/Bust", c: "label-boom" },
    "chrisgodwin": { s: 51.38, l: "Boom/Bust", c: "label-boom" },
    "joshdowns": { s: 50.92, l: "Boom/Bust", c: "label-boom" },
    "djmoore": { s: 50.77, l: "Boom/Bust", c: "label-boom" },
    "tretucker": { s: 50.57, l: "Boom/Bust", c: "label-boom" },
    "lutherburden": { s: 50.02, l: "Boom/Bust", c: "label-boom" },
    "cooperkupp": { s: 48.64, l: "Boom/Bust", c: "label-boom" },
    "kayshonboutte": { s: 48.61, l: "Boom/Bust", c: "label-boom" },
    "marquisebrown": { s: 48.30, l: "Boom/Bust", c: "label-boom" },
    "jerryjeudy": { s: 47.73, l: "Boom/Bust", c: "label-boom" },
    "dariusslayton": { s: 47.55, l: "Boom/Bust", c: "label-boom" },
    "mackhollins": { s: 47.39, l: "Boom/Bust", c: "label-boom" },
    "rashidshaheed": { s: 47.33, l: "Depth Player", c: "label-depth" },
    "xavierworthy": { s: 47.08, l: "Depth Player", c: "label-depth" },
    "jalencoker": { s: 46.91, l: "Depth Player", c: "label-depth" },
    "keoncoleman": { s: 46.43, l: "Depth Player", c: "label-depth" },
    "elicayomanor": { s: 46.18, l: "Depth Player", c: "label-depth" },
    "kendrickbourne": { s: 44.70, l: "Depth Player", c: "label-depth" },
    "ryanflournoy": { s: 44.43, l: "Depth Player", c: "label-depth" },
    "jaydenhiggins": { s: 44.34, l: "Depth Player", c: "label-depth" },
    "darnellmooney": { s: 43.77, l: "Depth Player", c: "label-depth" },
    "jalennailor": { s: 42.03, l: "Depth Player", c: "label-depth" },
    "sterlingshepard": { s: 41.83, l: "Depth Player", c: "label-depth" },
    "chimeredike": { s: 41.65, l: "Depth Player", c: "label-depth" },
    "tyquanthornton": { s: 41.32, l: "Depth Player", c: "label-depth" },
    "patbryant": { s: 40.93, l: "Depth Player", c: "label-depth" },
    "andreiiosivas": { s: 40.88, l: "Depth Player", c: "label-depth" },
    "xavierlegette": { s: 40.53, l: "Depth Player", c: "label-depth" },
    "adonaimitchell": { s: 40.25, l: "Depth Player", c: "label-depth" },
    "demariodouglas": { s: 39.55, l: "Depth Player", c: "label-depth" },
    "dontayvionwicks": { s: 39.48, l: "Depth Player", c: "label-depth" },
    "kavontaeturpin": { s: 39.30, l: "Depth Player", c: "label-depth" },
    "xavierhutchinson": { s: 39.23, l: "Depth Player", c: "label-depth" },
    "joshuapalmer": { s: 39.19, l: "Depth Player", c: "label-depth" },
    "devaughnvele": { s: 38.75, l: "Depth Player", c: "label-depth" },
    "matthewgolden": { s: 38.43, l: "Depth Player", c: "label-depth" },
    "calvinaustin": { s: 37.94, l: "Depth Player", c: "label-depth" },
    "olamidezaccheaus": { s: 37.60, l: "Depth Player", c: "label-depth" },
    "jujusmithschuster": { s: 36.92, l: "Depth Player", c: "label-depth" },
    "malikwashington": { s: 36.84, l: "Depth Player", c: "label-depth" },
    "vanjefferson": { s: 36.27, l: "Depth Player", c: "label-depth" },
    "cedrictillman": { s: 36.09, l: "Depth Player", c: "label-depth" },
    "tezjohnson": { s: 35.76, l: "Depth Player", c: "label-depth" },
    "demarcusrobinson": { s: 35.56, l: "Depth Player", c: "label-depth" },
    "marvinmims": { s: 35.56, l: "Depth Player", c: "label-depth" },
    "treharris": { s: 35.53, l: "Depth Player", c: "label-depth" },
    "rashodbateman": { s: 35.23, l: "Depth Player", c: "label-depth" },
    "christiankirk": { s: 35.22, l: "Depth Player", c: "label-depth" },
    "dyamibrown": { s: 35.09, l: "Depth Player", c: "label-depth" },
    "isaiahbond": { s: 34.98, l: "Depth Player", c: "label-depth" },
    "deandrehopkins": { s: 34.66, l: "Depth Player", c: "label-depth" },
    "gregdortch": { s: 34.58, l: "Depth Player", c: "label-depth" },
    "kalifraymond": { s: 34.52, l: "Depth Player", c: "label-depth" },
    "johnmetchie": { s: 34.39, l: "Depth Player", c: "label-depth" },
    "isaacteslaa": { s: 33.95, l: "Depth Player", c: "label-depth" },
    "brandincooks": { s: 33.90, l: "Depth Player", c: "label-depth" },
    "jaylinnoel": { s: 33.71, l: "Depth Player", c: "label-depth" },
    "xaviersmith": { s: 33.65, l: "Depth Player", c: "label-depth" },
    "jalentolbert": { s: 33.32, l: "Depth Player", c: "label-depth" },
    "tylerlockett": { s: 33.04, l: "Depth Player", c: "label-depth" },
    "timpatrick": { s: 31.76, l: "Depth Player", c: "label-depth" },
    "jackbech": { s: 31.63, l: "Depth Player", c: "label-depth" },
    "jaylinlane": { s: 31.44, l: "Depth Player", c: "label-depth" },
    "jahandotson": { s: 31.11, l: "Depth Player", c: "label-depth" },
    "isaiahwilliams": { s: 30.16, l: "Depth Player", c: "label-depth" },
    "adamthielen": { s: 29.97, l: "Depth Player", c: "label-depth" },
    "davidsills": { s: 28.51, l: "Depth Player", c: "label-depth" },
    "jordanwhittington": { s: 27.79, l: "Depth Player", c: "label-depth" },

    // Running Backs
    "christianmccaffrey": { s: 90.94, l: "Elite", c: "label-elite" },
    "bijanrobinson": { s: 87.38, l: "Elite", c: "label-elite" },
    "jonathantaylor": { s: 77.60, l: "Elite", c: "label-elite" },
    "devonachane": { s: 76.88, l: "High-End Starter", c: "label-high" },
    "jahmyrgibbs": { s: 76.84, l: "High-End Starter", c: "label-high" },
    "jamescook": { s: 72.43, l: "High-End Starter", c: "label-high" },
    "derrickhenry": { s: 66.92, l: "Strong Starter", c: "label-strong" },
    "chasebrown": { s: 64.24, l: "Strong Starter", c: "label-strong" },
    "kyrenwilliams": { s: 63.64, l: "Strong Starter", c: "label-strong" },
    "saquonbarkley": { s: 62.13, l: "Strong Starter", c: "label-strong" },
    "javontewilliams": { s: 61.74, l: "Strong Starter", c: "label-strong" },
    "dandreswift": { s: 61.20, l: "Strong Starter", c: "label-strong" },
    "omarionhampton": { s: 60.87, l: "Quality Contributor", c: "label-quality" },
    "travisetienne": { s: 60.73, l: "Quality Contributor", c: "label-quality" },
    "buckyirving": { s: 60.54, l: "Quality Contributor", c: "label-quality" },
    "camskattebo": { s: 59.96, l: "Quality Contributor", c: "label-quality" },
    "joshjacobs": { s: 59.93, l: "Quality Contributor", c: "label-quality" },
    "breecehall": { s: 59.57, l: "Quality Contributor", c: "label-quality" },
    "ashtonjeanty": { s: 58.63, l: "Quality Contributor", c: "label-quality" },
    "jaylenwarren": { s: 58.24, l: "Quality Contributor", c: "label-quality" },
    "ricodowdle": { s: 57.02, l: "Boom/Bust", c: "label-boom" },
    "jkdobbins": { s: 54.17, l: "Boom/Bust", c: "label-boom" },
    "kennethwalkeriii": { s: 53.79, l: "Boom/Bust", c: "label-boom" },
    "quinshonjudkins": { s: 53.04, l: "Boom/Bust", c: "label-boom" },
    "tonypollard": { s: 52.25, l: "Boom/Bust", c: "label-boom" },
    "tyronetracy": { s: 51.45, l: "Boom/Bust", c: "label-boom" },
    "kennethgainwell": { s: 51.22, l: "Boom/Bust", c: "label-boom" },
    "rhamondrestevenson": { s: 50.90, l: "Boom/Bust", c: "label-boom" },
    "treveyonhenderson": { s: 50.35, l: "Boom/Bust", c: "label-boom" },
    "aaronjones": { s: 48.73, l: "Depth Player", c: "label-depth" },
    "alvinkamara": { s: 47.88, l: "Depth Player", c: "label-depth" },
    "kimanividal": { s: 45.70, l: "Depth Player", c: "label-depth" },
    "woodymarks": { s: 45.67, l: "Depth Player", c: "label-depth" },
    "zachcharbonnet": { s: 45.43, l: "Depth Player", c: "label-depth" },
    "rjharvey": { s: 45.27, l: "Depth Player", c: "label-depth" },
    "kylemonangai": { s: 44.03, l: "Depth Player", c: "label-depth" },
    "davidmontgomery": { s: 42.91, l: "Depth Player", c: "label-depth" },
    "chubahubbard": { s: 41.15, l: "Depth Player", c: "label-depth" },
    "michaelcarter": { s: 40.61, l: "Depth Player", c: "label-depth" },
    "tyjaespears": { s: 39.99, l: "Depth Player", c: "label-depth" },
    "jacorycroskeymerritt": { s: 39.82, l: "Depth Player", c: "label-depth" },
    "rachaadwhite": { s: 39.73, l: "Depth Player", c: "label-depth" },
    "jordanmason": { s: 39.55, l: "Depth Player", c: "label-depth" },
    "kareemhunt": { s: 39.07, l: "Depth Player", c: "label-depth" },
    "isiahpacheco": { s: 37.93, l: "Depth Player", c: "label-depth" },
    "blakecorum": { s: 37.00, l: "Depth Player", c: "label-depth" },
    "chrisrodriguez": { s: 35.76, l: "Depth Player", c: "label-depth" },
    "bamknight": { s: 35.73, l: "Depth Player", c: "label-depth" },
    "tylerallgeier": { s: 33.42, l: "Depth Player", c: "label-depth" },
    "nickchubb": { s: 33.27, l: "Depth Player", c: "label-depth" },
    "emanuelwilson": { s: 32.33, l: "Depth Player", c: "label-depth" },
    "devinsingletary": { s: 32.14, l: "Depth Player", c: "label-depth" },
    "jaylenwright": { s: 30.90, l: "Depth Player", c: "label-depth" },
    "samajeperine": { s: 30.83, l: "Depth Player", c: "label-depth" },
    "bhayshultuten": { s: 28.55, l: "Depth Player", c: "label-depth" },
    "brianrobinson": { s: 25.66, l: "Depth Player", c: "label-depth" },
    "seantucker": { s: 25.06, l: "Depth Player", c: "label-depth" },
    "olliegordon": { s: 21.29, l: "Depth Player", c: "label-depth" }
};