#!/usr/bin/env node
// Rewrites one season's bye weeks in js/shared/data/byes.js from nflverse's schedule file.
//
//   node scripts/update-byes.mjs <season>                 # e.g. 2027; downloads games.csv
//   node scripts/update-byes.mjs <season> --csv <file>    # use a games.csv already on disk
//
// Run it each May, once the NFL publishes the schedule. A team's bye is the week (1-18) of the
// regular season (game_type REG) in which it has no game. nflverse writes the Rams as LA; the
// apps use LAR. Fails, changing nothing, unless every team in NFL_TEAMS (js/mls/constants.js)
// gets exactly one bye and the file has no team the apps don't know. Only that season's line in
// byes.js is replaced (or added, in season order); the other seasons' lines are left as they are.
//
// Schedule data: nflverse (https://github.com/nflverse/nfldata). No API key needed.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BYES_FILE = join(ROOT, 'js/shared/data/byes.js');
const GAMES_URL = 'https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv';
const TEAM_CODE_MAP = { LA: 'LAR' };
const WEEKS = 18;
const START_MARKER = '// --- BYE_WEEKS (generated by scripts/update-byes.mjs, one line per season) ---';
const END_MARKER = '// --- END BYE_WEEKS ---';

function fail(msg) {
    console.error(`update-byes: ${msg}`);
    process.exit(1);
}

function parseArgs(argv) {
    const args = { season: null, csv: null };
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === '--csv') args.csv = argv[++i];
        else if (/^\d{4}$/.test(argv[i])) args.season = Number(argv[i]);
        else fail(`unexpected argument "${argv[i]}". Usage: node scripts/update-byes.mjs <season> [--csv <file>]`);
    }
    if (!args.season) fail('give a season, e.g. node scripts/update-byes.mjs 2027');
    return args;
}

// The apps' team codes, read from the NFL_TEAMS array in js/mls/constants.js.
function readAppTeams() {
    const src = readFileSync(join(ROOT, 'js/mls/constants.js'), 'utf8');
    const m = src.match(/export const NFL_TEAMS\s*=\s*\[([^\]]*)\]/);
    if (!m) fail('could not find NFL_TEAMS in js/mls/constants.js');
    return [...m[1].matchAll(/"([A-Z]+)"/g)].map(x => x[1]);
}

// Minimal RFC 4180 CSV parser (quoted fields, doubled quotes, newlines inside quotes).
function parseCsv(text) {
    const rows = [];
    let row = [], field = '', inQuotes = false;
    for (let i = 0; i < text.length; i++) {
        const c = text[i];
        if (inQuotes) {
            if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
            else if (c === '"') inQuotes = false;
            else field += c;
        } else if (c === '"') inQuotes = true;
        else if (c === ',') { row.push(field); field = ''; }
        else if (c === '\n' || c === '\r') {
            if (c === '\r' && text[i + 1] === '\n') i++;
            row.push(field); rows.push(row); row = []; field = '';
        } else field += c;
    }
    if (field !== '' || row.length) { row.push(field); rows.push(row); }
    return rows;
}

async function loadGamesCsv(csvPath) {
    if (csvPath) return readFileSync(csvPath, 'utf8');
    console.log(`Downloading ${GAMES_URL}`);
    const res = await fetch(GAMES_URL);
    if (!res.ok) fail(`download failed: HTTP ${res.status}`);
    return res.text();
}

function computeByes(csvText, season, appTeams) {
    const [header, ...rows] = parseCsv(csvText);
    const col = (name) => {
        const i = header.indexOf(name);
        if (i < 0) fail(`games.csv has no "${name}" column`);
        return i;
    };
    const iSeason = col('season'), iType = col('game_type'), iWeek = col('week');
    const iAway = col('away_team'), iHome = col('home_team');
    const code = (t) => TEAM_CODE_MAP[t] || t;

    const played = new Map(appTeams.map(t => [t, new Set()]));
    let games = 0;
    for (const r of rows) {
        if (Number(r[iSeason]) !== season || r[iType] !== 'REG') continue;
        const week = Number(r[iWeek]);
        if (!Number.isInteger(week) || week < 1 || week > WEEKS) fail(`unexpected week "${r[iWeek]}" in ${season}`);
        for (const team of [code(r[iAway]), code(r[iHome])]) {
            if (!played.has(team)) fail(`team "${team}" in games.csv isn't in NFL_TEAMS`);
            played.get(team).add(week);
        }
        games++;
    }
    if (!games) fail(`no regular-season games for ${season} in games.csv (has the schedule been published?)`);

    const byes = {};
    const problems = [];
    for (const team of appTeams) {
        const off = [];
        for (let w = 1; w <= WEEKS; w++) if (!played.get(team).has(w)) off.push(w);
        if (off.length !== 1) problems.push(`${team}: ${off.length ? `weeks ${off.join(', ')}` : 'none'}`);
        else byes[team] = off[0];
    }
    if (problems.length) fail(`every team needs exactly one bye in weeks 1-${WEEKS} of ${season}:\n  ${problems.join('\n  ')}`);
    return { byes, games };
}

function rewriteByesFile(season, byes, appTeams) {
    const src = readFileSync(BYES_FILE, 'utf8');
    const lines = src.split('\n');
    const start = lines.findIndex(l => l.trim() === START_MARKER);
    const end = lines.findIndex(l => l.trim() === END_MARKER);
    if (start < 0 || end < start) fail('could not find the BYE_WEEKS markers in js/shared/data/byes.js');
    const indent = lines[start].match(/^\s*/)[0];
    const entry = `${indent}${season}: { ${appTeams.map(t => `${t}: ${byes[t]}`).join(', ')} },`;

    const seasonOf = (l) => Number((l.match(/^\s*(\d{4}):/) || [])[1]);
    const body = lines.slice(start + 1, end);
    const at = body.findIndex(l => seasonOf(l) === season);
    if (at >= 0) body[at] = entry;
    else {
        const after = body.findIndex(l => seasonOf(l) > season);
        body.splice(after < 0 ? body.length : after, 0, entry);
    }
    const out = [...lines.slice(0, start + 1), ...body, ...lines.slice(end)].join('\n');
    if (out === src) return false;
    writeFileSync(BYES_FILE, out);
    return true;
}

const { season, csv } = parseArgs(process.argv.slice(2));
const appTeams = readAppTeams();
if (appTeams.length !== 32) fail(`expected 32 teams in NFL_TEAMS, found ${appTeams.length}`);
const { byes, games } = computeByes(await loadGamesCsv(csv), season, appTeams);
const changed = rewriteByesFile(season, byes, appTeams);
console.log(`${season}: ${games} regular-season games; js/shared/data/byes.js ${changed ? 'updated' : 'already up to date'}`);
for (let w = 1; w <= WEEKS; w++) {
    const teams = appTeams.filter(t => byes[t] === w);
    if (teams.length) console.log(`  week ${w}: ${teams.join(', ')}`);
}
